//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_compra
    {
        public int IdDetalle_Compra { get; set; }
        public int IdProducto { get; set; }
        public int IdCompra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public int IdReporte { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto producto { get; set; }
        public virtual reporte reporte { get; set; }
    }
}
