//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int IdDetalle_Venta { get; set; }
        public int IdVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public int IdReporte { get; set; }
        public Nullable<int> Descuento { get; set; }
        public int IdProducto { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual reporte reporte { get; set; }
        public virtual venta venta { get; set; }
    }
}
