//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_compras
    {
        public int codigo_compra { get; set; }
        public string Fecha_Compra { get; set; }
        public string proveedor { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public string producto { get; set; }
        public string Descripcion { get; set; }
        public string categoria { get; set; }
    }
}
