//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ventas
    {
        public int codigo_venta { get; set; }
        public string tipo_pago { get; set; }
        public string producto { get; set; }
        public string Descripcion { get; set; }
        public string cliente { get; set; }
        public string vendedor { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string descuento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
        public string Fecha_Venta { get; set; }
    }
}
